ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path,include
from cart import views
app_name="cart"

urlpatterns = [
    path('addtocart/<n>',views.addtocart,name="addtocart"),
    path('cartview',views.cartview,name="cartview"),
    path('cart_remove/<n>',views.cart_remove,name="cart_remove"),
    path('full_remove/<n>',views.full_remove,name="full_remove"),
    path('orderform',views.orderform,name="orderform"),
    path('orderview',views.orderview,name="orderview"),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from shop import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path,include
from search import views
app_name="search"

urlpatterns = [
    path('',views.search,name="search"),

]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path,include
from shop import views
app_name="shop"
urlpatterns = [
    path('',views.allcategories,name='allcategories'),
    path('allproducts/<p>',views.allproducts,name='allproducts'),
    path('detail/<p>',views.detail,name='detail'),
    path('register',views.register,name="register"),
    path('login',views.user_login,name="login"),
    path('logout',views.user_logout,name="logout"),
]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User


class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.product.name

    def subtotal(self):
        return self.quantity*self.product.price


class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    ordered_date = models.DateTimeField(auto_now_add=True)
    address=models.TextField()
    phone=models.IntegerField()
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")
    def __str__(self):
        return self.product.name

class Account(models.Model):
    acctnum=models.IntegerField()
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):
        return str(self.acctnum)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/shop/models.py
from django.db import models

from django.contrib.auth.models import User

class Category(models.Model):
    name=models.CharField(max_length=20)
    desc=models.TextField()
    image=models.ImageField(upload_to="images/category",null=True,blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name=models.CharField(max_length=20)
    desc=models.TextField()
    image=models.ImageField(upload_to="images/product",null=True,blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

ecommerce/cart/views.py
from django.shortcuts import render
from shop.models import Product
from cart.models import Cart,Account,Order
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

@login_required
def cartview(request):
    u=request.user
    cart=Cart.objects.filter(user=u)
    total=0
    for i in cart:
        total+=i.quantity*i.product.price

    return render(request,'cartview.html',{'c':cart,'total':total})
@login_required
def addtocart(request,n):
    p=Product.objects.get(name=n)
    u=request.user          #current login user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(p.stock > 0):
           cart.quantity+=1
           cart.save()
           p.stock-=1
           p.save()
    except:
        if(p.stock > 0):
          cart=Cart.objects.create(product=p,user=u,quantity=1)
          cart.save()
          p.stock-=1
          p.save()
    return cartview(request)

@login_required
def cart_remove(request,n):
    p=Product.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(cart.quantity>1):
            cart.quantity -= 1
            cart.save()
            p.stock += 1
            p.save()
        else:
            cart.delete()
            p.stock += 1
            p.save()
    except:
        pass
    return cartview(request)

@login_required
def full_remove(request,n):
    p=Product.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)

        cart.delete()
        p.stock += cart.quantity
        p.save()

    except:
        pass
    return cartview(request)

@login_required
def orderform(request):
    if (request.method == "POST"):
        a = request.POST['a']
        ph = request.POST['ph']
        n = request.POST['n']

        u=request.user
        cart=Cart.objects.filter(user=u)

        total=0
        for i in cart:
            total += i.quantity * i.product.price


        try:
            num=int(n)
            ac=Account.objects.get(acctnum=num)
            if(ac.amount>=total):
                ac.amount=ac.amount-total
                ac.save()
                for i in cart:
                    o=Order.objects.create(user=u,product=i.product,address=a,phone=ph,no_of_items=i.quantity,order_status="paid")
                    o.save()
                cart.delete()
                msg="Your Order placed successfully"
                return render(request,'orderdetail.html',{'msg':msg})
            else:
                msg = "Insufficient Amount. You can't Place Order"
                return render(request, 'orderdetail.html', {'msg': msg})
        except:
            pass


    return render(request, 'orderform.html')

@login_required
def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u)
    return render(request,'orderview.html',{'o':o,'u':u.username})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

def search(request):
    query=""
    products=None
    if (request.method=="POST"):
        query=request.POST['q']
        if (query):
            products = Product.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))

    return render(request, 'search.html', {'query':query,'p':products})

ecommerce/shop/views.py
from django.shortcuts import render,redirect
from shop.models import Category,Product
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from django.contrib.auth import  authenticate,login,logout
from django.contrib.auth.models import User
def allcategories(request):
    c=Category.objects.all()
    return render(request,'category.html',{'c':c})

def allproducts(request,p):
    c=Category.objects.get(name=p)
    p=Product.objects.filter(category=c)
    return render(request,'product.html',{'c':c,'p':p})

def detail(request,p):
    p=Product.objects.get(name=p)
    return render(request,'detail.html',{'p':p})


def register(request):
    if (request.method == "POST"):
        u = request.POST['u']
        p = request.POST['p']
        cp = request.POST['cp']
        fname = request.POST['f']
        lname = request.POST['l']
        e = request.POST['e']

        if (p == cp):
            user= User.objects.create_user(username=u,password=p,first_name=fname,last_name=lname,email=e)
            user.save()
            return redirect('shop:allcategories')
        else:
            return HttpResponse("Passwords are not same")
    return render(request,'register.html')


def user_login(request):
    if (request.method == "POST"):
        u = request.POST['u']
        p = request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return redirect('shop:allcategories')
        else:
            return HttpResponse("Invalid Credentials")

    return render(request,'login.html')

@login_required
def user_logout(request):
    logout(request)
    return redirect('shop:login')

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<style>
    body
 {
  font-family: "Poppins", sans-serif;
  font-weight: 500;
  font-style: normal;
  background-color:#9da7f5;
}
.footer
{
height:40px;
width:100%;
text-align:center;
background-color:#030202;
position:fixed;
bottom:0;
left:0;
}
.navbar .navbar-light .navbar-nav .nav-link
    {
    background-color=black;
    color:white;
    font-weight:bold;
    }

.form-control
    {width:50%;
    position:center;
    }

</style>
<body>

<header>
    <div class="container-fluid">
        <center> <img src="{% static 'images/logo1.jpg' %}" height="100px" width="150px"></center>
    </div>
</header>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"> My SHOP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allcategories' %}">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Catogories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.name %}">{{i.name}}</a></li>
              {% endfor %}

          </ul>
          {% if user.is_authenticated %}

             <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:logout' %}">Logout</a>
        </li>
          {% if user.is_superuser == False %}
           <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping me-5"><sub class="ms-1">{{count}}</sub></i></a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:orderview' %}">Your Orders</a>
        </li>
          {% endif %}
          {% else %}
           <li class="nav-item">
          <a class="nav-link"  href="{% url 'shop:register' %}">Register</a>
        </li>
           <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:login' %}">Login</a>
        </li>
           {% endif %}

      </ul>
<form class="d-flex" method="POST" action="{% url 'search:search' %}">
          {% csrf_token %}
        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

    </div>
  </div>
</nav>

{% block content %}

{% endblock %}

<footer class="footer">
    <div class="container-fluid text-center">
        <p>&copy; Myshop@pvt ltd. All rights reserved.</p>
    </div>
</footer>
</body>
</html>

ecommerce/templates/cartview.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px;">
    <div class="row">
        <h4 class="text-center">Shopping Cart</h4>
        <div class="col-6 border border-1">
           <table class="table table-bordered text-center fs-5" style="border-color: black;">
                <tr>
                    <th colspan="5"> Cart Items</th>
                </tr>
                {% for i in c %}
                <tr>
                    <td><img src="{{i.product.image.url}}" height="150px" width="150px"></td>
                    <td><b>{{i.product.name}}</b><br>
                    <b>ProductID:{{i.product.id}}</b><br>
                    <b> Unit Price:{{i.product.price}}</b><br>
                    <b>Quantity:{{i.quantity}}</b><br>
                    </td>

                    <td>Subtotal:{{i.subtotal}}</td>
                    <td>
                        {% if i.product.stock > 0 %}
                        <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus text-danger fs-4"></i></a>
                        <a href="{% url 'cart:addtocart' i.product.name %}"><i class="fa-solid fa-circle-plus text-danger fs-4"></i></a>

                        <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash-can text-danger fs-4"></i></a>
                        {% else %}
                        <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus text-danger fs-4"></i></a>
                        <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash-can text-danger fs-4"></i></a>
                    {% endif %}</td>

                </tr>
                {% endfor %}
            </table>
    </div>


<div class="col-4 border border-1  ms-3">
    <table class="table table-bordered text-center fs-5" style="border-color: black;">
    <tr>
        <th colspan ="5">Check Out</th>
    </tr>
        <tr>
            <th>Total:{{total}}</th>
<!--            <span style="position:absolute;right:20px;"></span>-->
        </tr>
</table>
    <a href="{% url 'cart:orderform' %}" class="btn btn-danger">Place Order</a>
    <a href="{% url 'shop:allcategories' %}" class="btn btn-danger" >Continue Shoping</a>
</div>
    </div>

    {% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid" xmlns="http://www.w3.org/1999/html">
    <img src="{% static 'images/banner1.jpg' %}" height="450px" width="100%">
</div>
<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <h3 class="text-center fw-bold">Our Collections</h3>
    <p style="text-align:justify;line-height:2;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>

</div>
<div class="container-fluid mt-3" style="margin-bottom:100px;" >
    <div class="row">
        {% for i in c %}
            <div class="col-sm-4">
                <div class="card" style="width: 30rem;">
                    <img src="{{i.image.url}}" height="200px" width="100%" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title text-center">{{i.name}}</h5>
                        <a href="{% url 'shop:allproducts' i.name %}" style="position:relative;left:42%;"class="btn btn-primary">PRODUCTS</a>
                    </div>
                </div>
            </div>
         {% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container ">
    <div class="row mt-5">
        <div class="col-sm-4 me-5">
            <img src="{{p.image.url}}" height="400px" width="400px">
        </div>
        <div class="col-sm-6 me-5">
            <h2>{{p.name}}</h2>
            <p class="h4 mt-5 " style="text-align:justify;">{{p.desc}}</p>
            <h2 class="mt-4">{{p.price}}</h2>
            {{p.stock}}

            {% if user.is_superuser == True %}
            {% if p.stock == 0 %}

            <h2>Out Of Stock</h2>
            <a href="{% url 'admin:index' %}" class="btn btn-danger mt-3">ADD STOCK</a>
            {% else %}
            <h2>Product in Stock</h2>
            <a href="{% url 'admin:index' %}" class="btn btn-danger mt-3">ADD STOCK</a>
            {% endif %}

            {% else %}

            {% if p.stock == 0 %}
            <h2>Out Of Stock</h2>
            {% else %}
            <a href="{% url 'cart:addtocart' p.name %}" class="btn btn-danger mt-4">ADD TO CART</a>
            {% endif %}

{% endif %}
        </div>
    </div>
</div>





{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
Login
{% endblock %}
{% block content %}
<div class="container" style="margin-bottom:100px;">
<center>
<h3 class="mt-4">Login</h3>
        <form method="POST">
  {% csrf_token %}>
    <div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u"  placeholder="Enter the username">
</div>
<div class="mb-3">
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter the password">
</div>
            <div class="mb-3">

  <input type="submit" class="form-control">
</div>
        </form>
</center>
</div>
{% endblock %}

ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <h4 class="text-center text-success">{{msg}}</h4>
    <h4 class="text-center text-danger">Thank You....</h4>
    <h4 class="text-center"><a href="{% url 'shop:allcategories' %}">Continue Shopping</a></h4>
</div>

{% endblock %}

ecommerce/templates/orderform.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container" style="margin-bottom:100px;">
<center>
<h3 class="mt-4">Order Form</h3>
        <form method="POST">
  {% csrf_token %}
    <div class="mb-3">
  <label class="form-label">Address</label>
  <input type="text" class="form-control" name="a"  placeholder="Enter the address">
</div>
             <div class="mb-3">
  <label class="form-label">Phone</label>
  <input type="number" class="form-control" name="ph"  placeholder="Enter the phone number">
</div>
<div class="mb-3">
  <label class="form-label">Account Number</label>
  <input type="number" class="form-control" name="n" placeholder="Enter the account number">
</div>
            <div class="mb-3">

  <input type="submit" class="form-control">
</div>
        </form>
</center>
</div>
{% endblock %}

ecommerce/templates/orderview.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container ">
    <div class="row mt-5 ">
        <h4 class=" text-danger">Name of the Customer:{{u}}</h4>
        {% for i in o %}
        <div class="col-sm-4 mt-3" style="margin-left:100px;">
            <img src="{{i.product.image.url}}" height="200px" width="200px">
        </div>
        <div class="col-sm-6 text-center mt-3">
            <b>Product name:{{i.product.name}}</b><br>
            <b>Product price:{{i.product.price}}</b><br>
            <b>Delivery_address:{{i.address}}</b><br>
            <b>Customer phone:{{i.phone}}</b><br>
            <b>Ordered on:{{i.ordered_date}}</b><br>
            <b class="text-success">Delivery_status:{{i.delivery_status}}</b><br>
        </div>
        {% endfor %}
    </div>
</div>





{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div>
    <img src="{{c.image.url}}" height="450px" width="100%">
</div>
<div class="container-fluid mt-3" style="margin-bottom:100px">
    <h3 class="text-center fw-bold">{{c.name}}</h3>
    <p style="text-align:justify;line-height:2;">{{c.desc}}</p>


</div>
<div class="container-fluid mt-3" style="margin-bottom:100px;" >
    <div class="row">
        {% for i in p %}
            <div class="col-sm-4">
                <div class="card" style="width: 30rem;">
                    <img src="{{i.image.url}}" height="200px" width="100%" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title text-center">{{i.name}}</h5>
                        <h6 class="card-title text-center">{{i.price}}</h6>
                        <a href="{% url 'shop:detail' i.name %}" style="position:relative;left:42%;"class="btn btn-primary">Details</a>
                    </div>
                </div>
            </div>
         {% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container" style="margin-bottom:100px;">
<center>
<h3 class="mt-4">Register</h3>

    <form method="POST">
  {% csrf_token %}>
    <div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u"  placeholder="Enter the username">
</div>
<div class="mb-3">
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter the password">
</div>
<div class="mb-3">
  <label class="form-label">Confirm password</label>
  <input type="password" class="form-control" name="cp"  placeholder="Enter the confirm password">
</div>
  <div class="mb-3">
  <label class="form-label">Firstname</label>
  <input type="text" class="form-control" name="f" placeholder="enter the firstname">
</div>
  <div class="mb-3">
  <label class="form-label">Lastname</label>
  <input type="text" class="form-control" name="l" placeholder="enter the lastname">
</div>
        <div class="mb-3">
  <label class="form-label">Email</label>
  <input type="text" class="form-control" name="e" placeholder="enter the email">
</div>

<div class="mb-3">

  <input type="submit" class="form-control">
</div>
</form>
</center>
</div>
{% endblock %}

ecommerce/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid mt-3" style="margin-bottom:100px;" >
<center>
    <h5> You have Searched for {{query}}</h5></center>
    {% if p %}


    <div class="row">
        {% for i in p %}
            <div class="col-sm-3" style="margin-right:20px;margin-bottom:20px;">
                <div class="card" style="width: 25rem;">
                    <img src="{{i.image.url}}" height="200px" width="100%" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title text-center">{{i.name}}</h5>
                        <h6 class="card-title text-center">{{i.price}}</h6>
                        <a href="{% url 'shop:detail' i.name %}" style="position:relative;left:42%;"class="btn btn-primary">Details</a>
                    </div>
                </div>
            </div>
         {% endfor %}
    </div>
   </div>
    {% else %}
    <h6 class="text-center">No Results Found</h6>
    {% endif %}

</div>
{% endblock %}